### ISSUE TITLE
Add App Version Checker

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#103]
Similar to #88, only difference is this one wont force a user to update, they will be able to skip the update

**Comment by PatilShreyas** [comment]
I have developed such feature in my many apps. I'll contribute later, because I have ready code.

Just tell me, on which node app details are located?

In my app, I created `app` node in root as


```json
app
{
    "versionCode" : "XXXX",
    "url" : "APK URL"
}
```

**Comment by PatilShreyas** [comment]
I have developed such feature in my many apps. I'll contribute later, because I have ready code.

Just tell me, on which node, app details are located?

In my app, I created `app` node in root as


```json
app
{
    "versionCode" : "XXXX",
    "message" : "New features are....",
    "url" : "APK URL"
}
```

**Comment by PatilShreyas** [comment]
Yep!
