### ISSUE TITLE
add emoji support

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#3]
Add emoji support to chat

**Comment by Pritom14** [comment]
While typing a text, the `GBoard` already has support for emojis and I can send emojis.

Can you please elaborate the issue?

**Comment by yhdesai** [comment]
Yes, External Emojis are supported, but not every keyboard has emoji support, so it would be nice to have a emoji button which lets the user select emojis and add them.

**Comment by yhdesai** [comment]
Also support for some custom tech based emojis can be added
Custom emojis will be in the format :emojiname: which need to be rendered by the android client

**Comment by Pritom14** [comment]
Okay, let me get started on the `emoji button` for selecting emojis

**Comment by yhdesai** [comment]
If needed, You can contact me on any one of these https://yhdesai.github.io/shipr-social-links/

**Comment by Pritom14** [comment]
Sure, will do that

**Comment by Pritom14** [comment]
Please check #74
