### ISSUE TITLE
Add chat categories

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#44]
Add a spinner or any other component which can be used to switch the chat channels to different categories like general/help/channel 3/etc

**Comment by nikhilbansal97** [comment]
Is someone working on it?

**Comment by yhdesai** [comment]
No, Feel free to take it

**Comment by nikhilbansal97** [comment]
Okay, Cool 👍

**Comment by nikhilbansal97** [comment]
How many channels do we have? Can I have access to the firebase db?

**Comment by yhdesai** [comment]
The channels are
chat/general
chat/introductions
chat/help
chat/mt-general

**Comment by nikhilbansal97** [comment]
@yhdesai I have created a PR. Kindly review it when you get time.

**Comment by yhdesai** [comment]
Thanks for the PR, Will try to review it soon!

**Comment by yhdesai** [comment]
#67  fixes this
