### ISSUE TITLE
Star this repo.

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#48]
and check it out while you are here :)

**Comment by aavizek** [comment]
@yhdesai  what actually issue this? can you just elaborate a little?

**Comment by yhdesai** [comment]
Just using the Hacktoberfest for a little selfish self-promotion

**Comment by aavizek** [comment]
@yhdesai what exatcly i need to do to resolve this issue?i will work on that

**Comment by aavizek** [comment]
@yhdesai i did the same what's next?

**Comment by yhdesai** [comment]
closed until 1 October 2019
