### ISSUE TITLE
ASCII character tool

### ISSUE THREAD

**Issue by sami286** [Shipr-Hub/Shipr-Community-Android#55]
I think an ASCII character analysing tool would be very usefull for lots of developers since there are some non-diplaying characters that can cause problems.
Tell me what you think about it and I will start working on it :)
In what section should we include it?

**Comment by yhdesai** [comment]
Sounds good!
You can have the java file under the tools directory and the xml as tool_(toolname).xml
and you can add a button leading to your activity in fragment_tools_list.xml/ToolsList.java

**Comment by sami286** [comment]
I think that would be it :)
#57

**Comment by yhdesai** [comment]
Published
PR : #57 
Version Code : 21
Version Name : 0.4.5
