### ISSUE TITLE
Write a better README.md

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#59]

**Comment by alistairholmes** [comment]
Hi @yhdesai , how would you like me to write a better README.md file for you?

**Comment by yhdesai** [comment]
Readme Edited, Need to add site links and maybe a bit more info

**Comment by alistairholmes** [comment]
Sure, I would like to work on this issue, please provide the necessary site links and other info that you would want to added. Also would you mind me adding screenshots of the app and adding a license?

**Comment by alistairholmes** [comment]
#60 Updated README.md
