### ISSUE TITLE
Add a new Dev Tool

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#61]
Add any Developer Tool from the Tools list on the README.md or the Trello Board, or add one which you think will be a good developer tool.

**Comment by nikhilbansal97** [comment]
Hi, can I work on an SSH Client?

**Comment by yhdesai** [comment]
@nikhilbansal97 SSH client actually already exists, but feel free to work on improving the existing ssh client

**Comment by nikhilbansal97** [comment]
@yhdesai How can I improve it?

**Comment by yhdesai** [comment]
@nikhilbansal97  You could maybe work on the GUI section, or maybe go through the backend and try to see if something could be done in a better way, or feel free to come up with an entire new ssh client, You can do any of these.
