### ISSUE TITLE
remove notification of messages sent and received while app was open

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#68]

**Comment by Parthav46** [comment]
I have a solution for that. Can you first merge the channel PR so that I can generalize the solution?

**Comment by yhdesai** [comment]
@Parthav46 Go ahead and fix it on just the general channel, I plan to postpone the channel feature for some time.

**Comment by Parthav46** [comment]
I am replacing the notification service with firebasemessage service and a heroku server. This solution will also make notifications available for android O and P.

**Comment by yhdesai** [comment]
Awesome!
