### ISSUE TITLE
View Profile Option

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#87]
Clicking on a dp in chat opens up a profile view activity

**Comment by arshadkazmi42** [comment]
Is this still available? I can take this up. 
This looks a good first issue to start with the contribution to this.

**Comment by yhdesai** [comment]
Yes, Feel free to message me in the app chat if you need any help

**Comment by yhdesai** [comment]
ProfileActivity.java seems to be the EditProfile Activity, The View Profile Activity needs to be created. I will fix the naming.

**Comment by yhdesai** [comment]
Added an activity called activity_view_profile.xml for the same

**Comment by yhdesai** [comment]
file: MessageAdapter
Line 98 :  // TODO: 2/9/19 Edit this so that it does return the user uid
