### ISSUE TITLE
App crash on fast chat scrolling up

### ISSUE THREAD

**Issue by nixls** [Shipr-Hub/Shipr-Community-Android#89]
App crashes when rapidly scrolling up

**Comment by yhdesai** [comment]
This is really weird, If scrolled slowly, The Chat just seems to vanish, Looking into it.

**Comment by nixls** [comment]
Looks like app crashes on certain scroll point, ill take a look when ill be back home

**Comment by yhdesai** [comment]
Fixed, Thanks for notifying!
There apparently was a bugged message which was crashing the app

**Comment by yhdesai** [comment]
Do check it out on your side once @NikiGamePlay
